### ISSUE TITLE
Several elemet types

### ISSUE THREAD

**Issue by seryi70** [HidekiMori-CIT/aenet-lammps#1]
Dear developer,
I tried all permutations I could think of, to make lammps take a pair_coeff, but without success ( C-code is unreadable for me :) ). Can you,please, describe how a 2-element input would look like? For example TiO2 from aenet examples...
Thank you very much.
Sergiu

**Comment by HidekiMori-CIT** [comment]
Thank you for your contact.
At TiO2 of aenet example case, if you set atom type 1 is O and atom type 2 is Ti, pair_coeff becomes as follow,
pair_coeff * * v00 Ti O 10t-10t.nn O Ti
The order of first appeared elements is not important, so you can also write as 
pair_coeff * * v00 O Ti 10t-10t.nn O Ti
It is noted that if you use parameter file from example or made from original aenet, please use v00 at first item.

**Comment by seryi70** [comment]
Thank you very much. The issue I had is that I have one file per atomic species (Ti  Ti.10t-10t.nn, O    O.10t-10t.nn), now I understand that **args[5] is a filename mask, not filename, also important element symbol separated with a dot from the mask.** Please add this to the manual/instructions. 
Hopefully the ANN that I generated with aener v2.0.4 (they fixed few bugs) work correctly with your 2.0.3 patch. Any chance you update to the latest master branch?

**Comment by HidekiMori-CIT** [comment]
Thank you for your comment.
I have rewritten the description of setting name of parameter file.
If in case original version of discreptor (v00), I guess my patch work for 2.0.4 even have some warning and error at patching.
But I do not test in detail, so please contact me if you have any troubles and questions.

**Comment by HidekiMori-CIT** [comment]
I would like to make a patch for 2.0.4 (and later) soon.
Please wait.
