### ISSUE TITLE
Line87 in Makefile.in

### ISSUE THREAD

**Issue by Thesis-Appendix** [HidekiMori-CIT/aenet-lammps#2]
when I compile the aenet following the steps in README, the following error occurred.

cp: missing destination file operand after ‘../../Makefile.lammps’
Try 'cp --help' for more information.
make: *** [../../libaenet.a] Error 1

I guess the error is because the EXTRAMAKE is NULL. or other error?  How can I fix the error?

**Comment by HidekiMori-CIT** [comment]
Thank you for your information.
If you already get libaenet.a in lammps-(version)/lib/aenet/, most simple way to compile lammps with aenet is copy Makefile.lammps.gfortran as Makefile.lammps into  lammps-(version)/lib/aenet/ .  (If you use ifort please replace gfortran to ifort)
And Please proceed the compile following README.
Oterhwise, Please tell me OS, compiler (gfortran or ifrot), lammps version, aenet version (2.0.3 or 2.0.4), I would like to check.

**Comment by Thesis-Appendix** [comment]
Thank for your reply!
**OS**: Red Hat Enterprise Linux Server release 7.6 (Maipo)
**compiler**: ifort
**aenet**: 2.0.3

**======compile serial version======**
When I compile the aenet-lammps following the README
tar -xvzf lammps-stable.tar.gz
cp -r ./aenet-lammps/USER-AENET/ ./**lammps-3Mar20**/src/
cp -r ./aenet-lammps/aenet/ ./**lammps-3Mar20**/lib/
cp aenet-2.0.3.tar.bz2 **lammps-3Mar20**/lib/aenet/

cd **lammps-3Mar20**/lib/aenet/
tar -jvxf aenet-2.0.3.tar.bz2
patch -u -p1 -d aenet-2.0.3/ < aenet-2.0.3_lammps.patch
cd aenet-2.0.3/src/
make -f makefiles/**Makefile.ifort_serial** lib
cd ../../
cd ../../src/
make yes-user-aenet

Till now, everything is OK. 
When I do the finnal step: make mpi

the following error occurred：

/usr/bin/ld: ../../lib/aenet/libaenet.a(symmfunc.o): undefined reference to symbol '__libm_sse2_sincos'
/data/compiler/intel2018u4/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64_lin/libimf.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [../lmp_mpi] Error 1
make[1]: Leaving directory `/data/home/csy/zt/program/lammps/lammps-3Mar20/src/Obj_mpi'
make: *** [mpi] Error 2


**======compile mpi version======**

When I compile the aenet-lammps following the README
tar -xvzf lammps-stable.tar.gz
cp -r ./aenet-lammps/USER-AENET/ ./**lammps-3Mar20**/src/
cp -r ./aenet-lammps/aenet/ ./**lammps-3Mar20**/lib/
cp aenet-2.0.3.tar.bz2 **lammps-3Mar20**/lib/aenet/

cd **lammps-3Mar20**/lib/aenet/
tar -jvxf aenet-2.0.3.tar.bz2
patch -u -p1 -d aenet-2.0.3/ < aenet-2.0.3_lammps.patch
cd aenet-2.0.3/src/
Everything is OK.

When I do the step: make -f makefiles/**Makefile.ifort_mpi** lib

the following error occurred：

cp: missing destination file operand after ‘../../Makefile.lammps’
Try 'cp --help' for more information.
make: *** [../../libaenet.a] Error 1

**Comment by HidekiMori-CIT** [comment]
Thank you for your reply.
Then, please try following recipe.
At lammps-3Mar20/lib/aenet/
1. clean object files
 make -f makefiles/Makefile.ifort_serial veryclean
2. recompile aenet libraly.
 make -f makefiles/Makefile.ifort_serial lib
3. compile lammps at lammps-3Mar20/src/
make icc_mpich
or
make icc_openmpi
mpi option depends on your system. If you do not know, please ask admin.
